name: Docker Push CI

on: [release]

jobs:
  push:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      - name: Docker tag
        run: docker image tag frooooonk/androidsdk-gradle-nodejs frooooonk/androidsdk-gradle-nodejs:$RELEASE_VERSION

      - name: Docker push
        run: docker push frooooonk/androidsdk-gradle-nodejs:$RELEASE_VERSION
